name: Coverage

on: [push]

jobs:
  coverage:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: bench
          POSTGRES_USER: bencher
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Run code coverage
        run: |
          cargo xtask generate-code-coverage-report --install-dependencies

      - name: Deploy Docs
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: coverage/
          git-config-name: kl-botsu
          git-config-email: botsu@khonsulabs.com
          target-folder: /coverage/
          clean: true
